# Generated by Django 2.2.3 on 2022-07-26 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0004_auto_20220725_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('link', models.CharField(max_length=255, verbose_name='Link da Noticia')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem_galeria', models.ImageField(blank=True, upload_to='noticias/%Y/%m/%d', verbose_name='Imagem da noticia')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.Categoria', verbose_name='Categoria')),
            ],
        ),
    ]
