# Generated by Django 2.2.3 on 2022-07-26 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='imagem_galeria',
            new_name='imagem_noticia',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
