# Generated by Django 2.2.3 on 2022-07-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='noticia',
            name='link_video',
            field=models.CharField(max_length=255, null=True, verbose_name='Link do video'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='titulo_video',
            field=models.CharField(max_length=255, null=True, verbose_name='Titulo'),
        ),
    ]
