# Generated by Django 2.2.3 on 2022-07-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_auto_20220726_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='link_video',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='titulo_video',
        ),
    ]
