# Generated by Django 2.2.3 on 2022-07-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20220721_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='imagem',
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagem_galeria',
            field=models.ImageField(blank=True, upload_to='galerias/%Y/%m/%d', verbose_name='Imagem da galeria'),
        ),
    ]
