# Generated by Django 2.2.3 on 2022-07-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_galeria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
